group = "example"
project = "test"
[ext]

common_table_field_1 = """`scope`   VARCHAR(128) NOT NULL,
`user_id` BIGINT NOT NULL DEFAULT 0,
`year`    INT NOT NULL DEFAULT 0,"""

common_table_field_2 = """`scope`   VARCHAR(128) NOT NULL,
`user_id` BIGINT NOT NULL DEFAULT 0,"""

common_table_field_3 = """`scope`   VARCHAR(128) NOT NULL,
`year`    INT NOT NULL DEFAULT 0,"""

common_table_field_4 = """`scope`   VARCHAR(128) NOT NULL,"""

common_table_primary_1 = """PRIMARY KEY (`scope`,`user_id`,`year`)"""
common_table_primary_2 = """PRIMARY KEY (`scope`,`user_id`)"""
common_table_primary_3 = """PRIMARY KEY (`scope`,`year`)"""
common_table_primary_4 = """PRIMARY KEY (`scope`)"""

sum_table_name_1 = "accumulator_sum_scope_user_year"
sum_table_name_2 = "accumulator_sum_scope_user"
sum_table_name_3 = "accumulator_sum_scope_year"
sum_table_name_4 = "accumulator_sum_scope"

sum_data_type = "DECIMAL(35, 15)"
sum_data_default = "0.0"

sum_day_count_type = "DECIMAL(10, 0)"
sum_month_count_type = "DECIMAL(12, 0)"
sum_year_count_type = "DECIMAL(15, 0)"
sum_count_default = "0"

max_table_name_1 = "accumulator_max_scope_user_year"
max_table_name_2 = "accumulator_max_scope_user"
max_table_name_3 = "accumulator_max_scope_yea"
max_table_name_4 = "accumulator_max_scope"

max_data_type = "DECIMAL(35, 15)"
max_data_default = "0.0"

min_table_name_1 = "accumulator_min_scope_user_year"
min_table_name_2 = "accumulator_min_scope_user"
min_table_name_3 = "accumulator_min_scope_yea"
min_table_name_4 = "accumulator_min_scope"

min_data_type = "DECIMAL(35, 15)"
min_data_default = "0.0"
