project_structure = [

    {item_path = ".",  item_file = "full.sql", item_tmpl = "full.sql.tmpl", item_type = "static"},

    {item_path = ".",  item_file = "sum1.sql", item_tmpl = "sum.sql.1.tmpl", item_type = "static"},
    {item_path = ".",  item_file = "sum2.sql", item_tmpl = "sum.sql.2.tmpl", item_type = "static"},
    {item_path = ".",  item_file = "sum3.sql", item_tmpl = "sum.sql.3.tmpl", item_type = "static"},
    {item_path = ".",  item_file = "sum4.sql", item_tmpl = "sum.sql.4.tmpl", item_type = "static"},

    {item_path = ".",  item_file = "max1.sql", item_tmpl = "max.sql.1.tmpl", item_type = "static"},
    {item_path = ".",  item_file = "max2.sql", item_tmpl = "max.sql.2.tmpl", item_type = "static"},
    {item_path = ".",  item_file = "max3.sql", item_tmpl = "max.sql.3.tmpl", item_type = "static"},
    {item_path = ".",  item_file = "max4.sql", item_tmpl = "max.sql.4.tmpl", item_type = "static"},

    {item_path = ".",  item_file = "min1.sql", item_tmpl = "min.sql.1.tmpl", item_type = "static"},
    {item_path = ".",  item_file = "min2.sql", item_tmpl = "min.sql.2.tmpl", item_type = "static"},
    {item_path = ".",  item_file = "min3.sql", item_tmpl = "min.sql.3.tmpl", item_type = "static"},
    {item_path = ".",  item_file = "min4.sql", item_tmpl = "min.sql.4.tmpl", item_type = "static"}   
]